EDGShoppingCart/Pages/Products/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EDGShoppingCart.Data;
using EDGShoppingCart.Models;
using EDGShoppingCart.Repositories.Interfaces;
using EDGShoppingCart.Repositories;

namespace EDGShoppingCart.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly EDGShoppingCart.Data.EDGShoppingCartContext _context;
        private readonly ICartRepository _cartRepository;
        private readonly IDiscountRepositry _discountRepository;

        public IndexModel(EDGShoppingCart.Data.EDGShoppingCartContext context, ICartRepository cartRepository, IDiscountRepositry discountRepository)
        {
            _context = context;
            _cartRepository = cartRepository ?? throw new ArgumentNullException(nameof(cartRepository));
            _discountRepository = discountRepository ?? throw new ArgumentNullException(nameof(discountRepository));
        }

        public IEnumerable<Models.Product> Products { get; set; } = new List<Models.Product>();
        public int PromoFlag
        {
            get
            {
                return _discountRepository.GetFlagValue("EDG");
            }
        }
        public async Task OnGetAsync()
        {
            if (_context.Product != null)
            {
                Products = await _context.Product.ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            await _cartRepository.AddItem("EDG", productId);
            return RedirectToPage("/Cart/Index");
        }

    }
}

EDGShoppingCart/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EDGShoppingCart</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600" rel="stylesheet" type="text/css">
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    
    <link rel="stylesheet" href="~/EDGShoppingCart.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-page="/Index">Home</a>
                <a class="navbar-brand" asp-page="/Discounts/Index">Discounts</a>
                <a class="navbar-brand" asp-page="/Products/Index">Products</a>
                <a class="navbar-brand" asp-page="/Cart/Index">Cart</a>
                <form class="form-inline my-2 my-lg-0">
                    <a class="btn btn-success btn-sm ml-3" asp-area="" asp-page="/Cart/Index">
                        <i class="fa fa-shopping-cart"></i> Cart
                    </a>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- JS -->
    <script src="//code.jquery.com/jquery-3.2.1.slim.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        //Plus & Minus for Quantity product
        $(document).ready(function () {
            var quantity = 1;

            $('.quantity-right-plus').click(function (e) {
                e.preventDefault();
                var quantity = parseInt($('#quantity').val());
                $('#quantity').val(quantity + 1);
            });

            $('.quantity-left-minus').click(function (e) {
                e.preventDefault();
                var quantity = parseInt($('#quantity').val());
                if (quantity > 1) {
                    $('#quantity').val(quantity - 1);
                }
            });

        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EDGShoppingCart/Pages/Shared/_ProductItemMini.cshtml
@model EDGShoppingCart.Models.Product

<div class="card">
    <a asp-page="ProductDetail/Index" asp-route-productId="@Model.Id"><img asp-append-version="true" class="card-img-top" src="~/images/product/@Model.ImageFile" alt=""></a>
    <div class="card-body">
        <h4 class="card-title"><a asp-page="/ProductDetail/Index" asp-route-productId="@Model.Id" class="color-main">@Model.Name</a></h4>
        <p class="card-text">@Model.BeerType</p>
        <div class="row">
            <div class="col">
                <p class="btn btn-danger btn-block">$@Model.DiscountPrice</p>
            </div>
            <div class="col">

                <form asp-page-handler="AddToCart" method="post" name="addToCartForm" id="add_cart_form">
                    <a href="javascript:;" onclick="parentNode.submit();" class="btn btn-success btn-block">Add to Cart</a>
                    <input type="hidden" asp-for="@Model.Id" name="productId" />
                </form>

            </div>
        </div>
    </div>
</div>