EDGShoppingCart/Models/Cart.cs
namespace EDGShoppingCart.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public List<CartItem> Items { get; set; } = new List<CartItem>();

        public decimal BuyGetFreeDiscountTotal { get ; set; }          // This should be a negative number for the Coopers promo

        public decimal SpendOverFiftyDiscountTotal { get; set; }

        public decimal TotalPrice
        {
            get 
            {
                decimal totalprice = 0;
                foreach (var item in Items)
                {
                    totalprice += item.Price * item.Quantity;
                }
                return totalprice + BuyGetFreeDiscountTotal + SpendOverFiftyDiscountTotal;
            }
        }
    }
}

EDGShoppingCart/Pages/Cart/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EDGShoppingCart.Models;
using EDGShoppingCart.Repositories.Interfaces;
using EDGShoppingCart.Repositories;

namespace EDGShoppingCart.Pages.Cart
{
    public class IndexModel : PageModel
    {
        private readonly ICartRepository _cartRepository;
        private readonly IDiscountRepositry _discountRepository;

        public IndexModel(ICartRepository cartRepository, IDiscountRepositry discountRepository)
        {
            _cartRepository = cartRepository ?? throw new ArgumentNullException(nameof(cartRepository));
            _discountRepository = discountRepository ?? throw new ArgumentNullException(nameof(discountRepository));
        }

        public Models.Cart Cart { get; set; } = new Models.Cart();
        public int PromoFlag
        {
            get
            {
                return _discountRepository.GetFlagValue("EDG");
            }
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Cart = await _cartRepository.GetCartByUserName("EDG");
            CheckPromo();
            return Page();
        }

        public async Task<IActionResult> OnPostRemoveFromCartAsync(int cartId, int cartItemId)
        {
            await _cartRepository.RemoveItem(cartId, cartItemId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostUpdateCartAsync(Dictionary<int, int> cartItemQuantities)
        {
            Cart = await _cartRepository.GetCartByUserName("EDG");

            foreach (var cartItem in Cart.Items)
            {
                if (cartItemQuantities.ContainsKey(cartItem.Id))
                {
                    int updatedQuantity = cartItemQuantities[cartItem.Id];
                    cartItem.Quantity = updatedQuantity;

                    await _cartRepository.UpdateQuantityCartItem(Cart.Id, cartItem.Id, updatedQuantity);
                }
            }

            return RedirectToPage();
        }

        private void CheckPromo()
        {
            if (Cart != null)
            {
                
                int coopersFreeTotal = 0;
                decimal singleCoopers = 0;
                foreach (var cartItem in Cart.Items)
                {
                    if ((PromoFlag & (int)Global.PromotionFlags.VB) == (int)Global.PromotionFlags.VB)
                    {
                        if ((cartItem.Product.PromoFlag & (int)Global.PromotionFlags.VB) == (int)Global.PromotionFlags.VB)
                        {
                            cartItem.Price = cartItem.Product.Price - 2;
                        }
                    }

                    if ((PromoFlag & (int)Global.PromotionFlags.Coopers) == (int)Global.PromotionFlags.Coopers)
                    {
                        if ((cartItem.Product.PromoFlag & (int)Global.PromotionFlags.Coopers) == (int)Global.PromotionFlags.Coopers)
                        {
                            coopersFreeTotal += cartItem.Quantity;
                            singleCoopers = cartItem.Product.Price;
                        }
                    }
                }

                if (coopersFreeTotal > 0)
                {
                    Cart.BuyGetFreeDiscountTotal = (-singleCoopers * (coopersFreeTotal / 2));
                }

                if ((PromoFlag & (int)Global.PromotionFlags.SpendFifty) == (int)Global.PromotionFlags.SpendFifty)
                {
                    if (Cart.TotalPrice > 49)
                    {
                        Cart.SpendOverFiftyDiscountTotal = -5;
                    }
                }
            }
        }
    }
}

EDGShoppingCart/Pages/Cart/Index.cshtml
@page
@model EDGShoppingCart.Pages.Cart.IndexModel
@{
    ViewData["Title"] = "Cart";
}

<div class="container">
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Promotional Code @Model.PromoFlag.ToString()</li>
                </ol>
            </nav>
        </div>
    </div>
</div>

<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col" class="text-center">Quantity</th>
                            <th scope="col" class="text-center">Single Price</th>
                            <th scope="col" class="text-right">Quantity Price</th>
                            <th scope="col" class="text-right">Product Discount Price</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        
                            @foreach (var cartItem in Model.Cart.Items)
                            {
                            <tr>
                                <td>@cartItem.Product.Name</td>
                                <form method="post" id="updateCartForm" asp-page-handler="UpdateCart">
                                    <td>
                                        <input class="form-control" type="number" id="cartItemQuantity_@cartItem.Id" value="@cartItem.Quantity" min="1" max="100" data-id="@cartItem.Id" onchange="submitUpdateCartForm(this)" />
                                    </td>
                                    <button type="submit" style="display: none"></button>
                                </form>
                                <td class="text-right" id="SinglePrice_@cartItem.Id">@(cartItem.Product.Price.ToString("C2"))</td>
                                <td class="text-right" id="totalPrice_@cartItem.Id">$@(cartItem.Product.Price * cartItem.Quantity)</td>
                                <td class="text-right" id="totalDiscountPrice_@cartItem.Id">$@(cartItem.Price * cartItem.Quantity)</td>
                                <td class="text-right">
                                    <form asp-page-handler="RemoveFromCart" method="post">
                                        <button class="btn btn-sm btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                                        <input type="hidden" asp-for="@Model.Cart.Id" name="cartId" />
                                        <input type="hidden" asp-for="@cartItem.Id" name="cartItemId" />
                                    </form>
                                </td>
                            </tr>
                            <input type="hidden" asp-for="Cart.Items" name="Cart.Items" value="@cartItem.Id" />
                            }
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Buy One Get On Free Discount</strong></td>
                            <td class="text-right"><strong id="BOGOF">@Model.Cart.BuyGetFreeDiscountTotal.ToString("C2")</strong></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Spend over $ Discount</strong></td>
                            <td class="text-right"><strong id="SpendOver">@Model.Cart.SpendOverFiftyDiscountTotal.ToString("C2")</strong></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td class="text-right"><strong id="grandTotal">@Model.Cart.TotalPrice.ToString("C2")</strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    function submitUpdateCartForm(input) {
        var cartItemId = input.getAttribute("data-id");
        var quantity = input.value;

        if (quantity < 0) {
            quantity = 0; // Set the value to 0 if negative number is entered
        }

        var form = document.getElementById("updateCartForm");
        var hiddenInput = document.createElement("input");
        hiddenInput.setAttribute("type", "hidden");
        hiddenInput.setAttribute("name", "CartItemQuantities[" + cartItemId + "]");
        hiddenInput.setAttribute("value", quantity);
        form.appendChild(hiddenInput);

        form.submit();
    }
</script>